import { c as create_ssr_component } from "../../../chunks/ssr.js";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: '.installation-section.s-taHFxyWwyJX1{background-image:url("$lib/img/HeroBanner.webp");background-size:cover;height:calc(100vh - 90px)}.installation-container.s-taHFxyWwyJX1{box-sizing:border-box;display:flex;flex-direction:column;justify-content:space-around;align-items:center;position:relative;left:50%;top:50%;transform:translate(-50%, -50%);width:88vw;height:calc(88vh - 90px);border-radius:15px;background-color:var(--dark-transparency);padding:40px 50px}.installation-title.s-taHFxyWwyJX1{font-size:240%;font-weight:600;color:var(--main-color);margin:0;padding:0}.installation-option-container.s-taHFxyWwyJX1{display:flex;justify-content:space-between;align-items:center;width:45vw}.installation-option-title.s-taHFxyWwyJX1{font-size:125%;font-weight:500;color:var(--main-color);margin:0;padding:0}.installation-option.s-taHFxyWwyJX1{width:30vw;height:7vh;border-radius:8px;background-color:var(--transparent);outline-color:var(--main-color);outline-width:1px;outline-style:solid;display:flex;justify-content:center;align-items:center}.installation-option.s-taHFxyWwyJX1:hover{background-color:var(--dark-transparency);transition:0.3s}.installation-button.s-taHFxyWwyJX1{position:relative;display:block;background-color:var(--transparent);color:var(--main-color);border-style:solid;border-color:var(--main-color);border-width:1px;border-radius:8px;padding:15px;width:45vw;font-size:95%;font-weight:500}.installation-button.s-taHFxyWwyJX1:hover{background-color:var(--dark-transparency);transition:0.3s}a.s-taHFxyWwyJX1{text-decoration:none;color:var(--main-color)}',
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<section class="installation-section s-taHFxyWwyJX1"><div class="installation-container s-taHFxyWwyJX1"><h2 class="installation-title s-taHFxyWwyJX1" data-svelte-h="svelte-t5y3zs">Install Sigma</h2> <div class="installation-option-container s-taHFxyWwyJX1"><h4 class="installation-option-title s-taHFxyWwyJX1" data-svelte-h="svelte-33u7zi">Edition</h4> <div class="installation-option s-taHFxyWwyJX1" data-svelte-h="svelte-16r79rl">Classic</div></div> <div class="installation-option-container s-taHFxyWwyJX1"><h4 class="installation-option-title s-taHFxyWwyJX1" data-svelte-h="svelte-18w0loc">Version</h4> <div class="installation-option s-taHFxyWwyJX1" data-svelte-h="svelte-y1op6y">1.0.4</div></div> <div class="installation-option-container s-taHFxyWwyJX1"><h4 class="installation-option-title s-taHFxyWwyJX1" data-svelte-h="svelte-q66g8z">Theme</h4> <div class="installation-option s-taHFxyWwyJX1" data-svelte-h="svelte-702fc8">Symplex Green</div></div> <div class="installation-option-container s-taHFxyWwyJX1"><h4 class="installation-option-title s-taHFxyWwyJX1" data-svelte-h="svelte-w2ao68">Username</h4> <div class="installation-option s-taHFxyWwyJX1" data-svelte-h="svelte-am7lm1">preview</div></div> <a href="./" download="epsilon.onboarding.A.bin" class="s-taHFxyWwyJX1"><button class="installation-button s-taHFxyWwyJX1" data-svelte-h="svelte-j5lcex">Download Sigma</button></a></div></section>`;
});
export {
  Page as default
};
